### ISSUE TITLE
Consider --config option to reposync

### ISSUE THREAD

**Issue by blalor** [cavaliercoder/y10k#2]
Seems cleaner than managing repo-specific files in `/etc/yum.repos.d`.

**Comment by cavaliercoder** [comment]
That would be a much better way of doing things. I did experiment with this and had no luck. Can't remember why. But I will explore this again thank.

**Comment by blalor** [comment]
I believe it expects a complete yum.conf, not just a snippet describing a single repo.  Not sure if that helps. :-)

**Comment by beddari** [comment]
Yes it does, this is a complete working example https://gitlab.arif-ali.co.uk/arif/openstack-lab/tree/master/reposync

**Comment by cavaliercoder** [comment]
Thanks gents. Got it working in the end! The challenge last time was that Yum defaults to loading repos from `/etc/yum.repos.d` and was loading extra noise. By adding `reposdir=` to my isolated `yum.conf`, the problem is fixed and we are in business! I've just released v0.2.0 which uses the isolated config file method instead of temp repo files dirtying up the OS.

I've also added full support for all `yum.conf` directives in a Yumfile and some additional Yumfile options to further configure `reposync`.
